### ISSUE TITLE
res = (ort_session.run(None, {"data": img}))

### ISSUE THREAD

**Issue by charming2992** [cqu20160901/yolov7_caffe_onnx_tensorRT_rknn_horizon#1]
测试.onnx时候的报错问题
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid Feed Input Name:data

**Comment by charming2992** [comment]
这个问题是把data为images
又出现了新的问题，结果出现了几千个框
![image](https://user-images.githubusercontent.com/106571854/220101389-22bcef30-1c8d-4b28-82ad-a0838f48551f.png)

**Comment by cqu20160901** [comment]
“结果出现了几千个框”是用的我的例子，还是重新训练的模型导出onnx模型？

**Comment by charming2992** [comment]
> 

是使用的yolov7训练的我自己的数据集导出的ONNX，请问导出的时候有什么注意的地方吗，现在还没解决这个问题

**Comment by cqu20160901** [comment]
我给出的示例导出onnx时去除了卷积层之后所有的操作，后处理要适配

**Comment by charming2992** [comment]
> 我给出的示例导出onnx时去除了卷积层之后所有的操作，后处理要适配

请问可以提供一下吗，方便的话可以加一个别的联系方式吗

**Comment by cqu20160901** [comment]
在readme中增加了导出onnx的说明链接，可以参考。
![1676949402392](https://user-images.githubusercontent.com/22290931/220238751-894ba9ae-e39e-4dea-a65f-6adaa172b050.png)

**Comment by charming2992** [comment]
> 

您好，按照您给的导出的方法中修改了相关导出代码，现在依旧是这个问题。
运行yolov7_onnx_test.py之后的输出如下：
This is main .... 
0 (1, 19200, 8)
1 (1, 4800, 8)
2 (1, 1200, 8)
postprocess ... 
detectResult: 45397
6204

大佬可以帮忙看一下吗，onnx模型如下附件，CLASSES = ['cigarette','leaf','tissue']
[yolov7_tiny.zip](https://github.com/cqu20160901/yolov7_caffe_onnx_tensorRT_rknn_horizon/files/10790414/yolov7_tiny.zip)

**Comment by cqu20160901** [comment]
导出的 onnx 不对，确定是按照我的方式导出的？导出的维度不对




ZhangQian
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cqu20160901/yolov7_caffe_onnx_tensorRT_rknn_horizon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月21日(星期二) 下午2:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cqu20160901/yolov7_caffe_onnx_tensorRT_rknn_horizon] res = (ort_session.run(None, {"data": img})) (Issue #1)





   
您好，按照您给的导出的方法中修改了相关导出代码，现在依旧是这个问题。
 运行yolov7_onnx_test.py之后的输出如下：
 This is main ....
 0 (1, 19200, 8)
 1 (1, 4800, 8)
 2 (1, 1200, 8)
 postprocess ...
 detectResult: 45397
 6204
 
大佬可以帮忙看一下吗，onnx模型如下附件，CLASSES = ['cigarette','leaf','tissue']
 yolov7_tiny.zip

**Comment by cqu20160901** [comment]
时间太久了可能给出的修改地方没有完整，你再试试，我把完整的yolo.py文件贴在参考的博客中了。

**Comment by charming2992** [comment]
感谢，解决了。
应该是转onnx时候sigmoid的问题，之前转换的都是把sigmoid写进onnx中了（这样对于部署应该是好的吧，可以用npu加速）

**Comment by cqu20160901** [comment]
这个要看每款芯片的特性，如果芯片支持可以用npu减速，并不是每款芯片都支持sigmoid的，如果芯片不支持或者是芯片也是用CPU做的，自己实现可以考虑用近似sigmoid。


ZhangQian
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cqu20160901/yolov7_caffe_onnx_tensorRT_rknn_horizon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月21日(星期二) 下午4:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cqu20160901/yolov7_caffe_onnx_tensorRT_rknn_horizon] res = (ort_session.run(None, {"data": img})) (Issue #1)





 
感谢，解决了。
 应该是转onnx时候sigmoid的问题，之前转换的都是把sigmoid写进onnx中了（这样对于部署应该是好的吧，可以用npu加速）
